pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mkdir .gzipped
  - cp -r * .gzipped
  - gzip -r .gzipped
  - cp -r .gzipped/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - production
